### ISSUE TITLE
Enviromine Statistics Not Ticking

### ISSUE THREAD

**Issue by C222** [Funwayguy/EnviroMine#109]
All statistics are not being tracked on SMP server for all players.

[Illustration of issue](https://www.youtube.com/watch?v=G49F2I5wPko)

**Comment by Funwayguy** [comment]
I think I've solved this for the next update and just in case I put in an extra check to make sure if a tracker somehow goes missing server-side it will be restored.

**Comment by C222** [comment]
Just for good measure, here's my server's GC settings:

```
-XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -XX:PermSize=128m -XX:MaxPermSize=256m
```

**Comment by C222** [comment]
Version 1.3.99 Still has no tracking. Worked fine after the first connection. Seems to go away after disconnecting once.
Can we get a log message in the constructor and destructor of the tracker class?

**Comment by Funwayguy** [comment]
Yea I might need to do just that because I have no idea what broken method seems to be removing the trackers and why. I'll make another attempt at fixing it as well as adding the logging next update.

**Comment by GenDeathrow** [comment]
@Funwayguy should have this fixed in build 1.3.101.. fingers crossed

**Comment by C222** [comment]
Tracking seems to always be on nowadays. 
However, clamping to safe range seems to break at extreme values? Still get players dying in a loop if they fall in lava or the like.

**Comment by GenDeathrow** [comment]
This Is funwayguy a system. But I have been rewriting it latly for a much later update. I was wonder why the clamp safe updates were there.  I will look at his stuff and see if I can figure out what happening. he had been super busy right now.

**Comment by Funwayguy** [comment]
Safe range clamping should bring the player's temp between 35-39C (95-102F) which yes is on the edge of Heatstroke 1 so players should immediately find water or a cool spot after respawning.
